### ISSUE TITLE
Fixed Key Vault Option

### ISSUE THREAD

**Issue by jhunt** [jhunt/ssg#12]
Most of the time, using ranomized keying material is best.  Other times, knowing the key used to decrypt, out-of-band or a priori, is more valuable.  For the latter case, it would be nice if we could configure the vault (regardless of backend) with a fixed key, stored somewhere in the vault, and use that key to consistently derive keying material via PBKDF2.

Configuration would look something like this:

```
vault:
  fixedKey:
    pbkdf2: some/path/that/means/something/to/the/provider

  provider: foo
  foo:
    fooDetails: here
```

The important things to note here are (a) the provider configuration is not part of the fixed-vs-rotate decision, but (b) the provider has to understand what to do with the path, and (c) we may need to support different key sources in the future, i.e.:

```
vault:
  fixedKey:
    aes128:
      key: path/to/key/in/vault
      iv: path/to/iv/in/vault
    aes192:
      key: path/to/key/in/vault
      iv: path/to/iv/in/vault
    aes256:
      key: path/to/key/in/vault
      iv: path/to/iv/in/vault
```

... although that is not required right now -- all we need for right now is PBKDF2 support.
