### ISSUE TITLE
Ephemeral Provider for Tests

### ISSUE THREAD

**Issue by jhunt** [jhunt/ssg#19]
For testing other projects that are integrating with SSG, it would be nice to have an 'ephemeral', in-memory provider that just puts files in a hash resembling the filesystem.

Something like:

```
buckets:
  - key: ephemeral
    provider:
      kind: ephemeral
```

(there is not other configuration...)
