### ISSUE TITLE
Multiple Buckets / Backends

### ISSUE THREAD

**Issue by jhunt** [jhunt/ssg#5]
SSG needs to support multiple backend types, and multiple buckets.

A "backend" is a logic thing that rolls up the necessary configuration parameter definitions (I need a key, I need an endpoint, etc.) and the business logic to interact with a type of storage.  "S3" is a backend.

A "bucket" is a specific configuration of a backend, with values for the backend parameters (here is the key, here is the endpoint, etc.), and configuration for retention, compression, and encryption of snapshots in the bucket.

We already have the backend stuff today (inmem, file, soon: S3).

We need to implement buckets and their configuration statically (by the SSG operator) and dynamic discovery of bits of that configuration (by the SHIELD scheduler using the SSG).

Here's an example form the SHIELD v9 project:

```
---
# /etc/shield/gateway.yml
shield: v9
storage-gateway:
  cluster: main
  bind: *:9999

  control:
    username: admin
    password: $ADMIN_PASSWORD

  defaultBucket:
    maxSnapshotRetention: 14d
    compression: lzma
    encryption: aes256-gcm

    vault:
      kind: hashicorp
      hashicorp:
        url: https://vault.corp/
        prefix: /secret/foo/shield/stuff   # default to /secret/shield
        roleID: foo
        secretID: bar...
        caCertificate:
          literal: $VAULT_CA

  buckets:
    - key: s3-cheap               # <-- for SSG API control interaction
      name: Nearline (Compressed) # <-- for Job dropdown store selection
      description: |
        Cheap, fast, always-available cloud storage,
        on Amazon AWS, with ZERO dependencies on our
        VPCs, cross-connects, and backhaul network.

        These snapshots are encrypted at rest by
        Jeff Bezos himself.

      maxSnapshotRetention: 90d
      compression: xz
      encryption: none

      # ^^ public information

      config: &s3-cheap
        vault: &kms # this overrides COMPLETELY
          kind: amazon
          amazon: ...

       kind: s3
        s3:
          region: us-east-1
          bucket: all-our-shield-backups
          aki: AKI....
          key: sekrit....
          prefix: /backups

    - key: s3-cheap-uncompressed   # <-- for SSG API control interaction
      name: Nearline (!Compressed) # <-- for Job dropdown store selection
      description: |
        Cheap, fast, always-available cloud storage,
        on Amazon AWS, with ZERO dependencies on our
        VPCs, cross-connects, and backhaul network.

        (This is an uncompressed storage)

      config: *s3-cheap # bring in all the details from the other store

      maxSnapshotRetention: 90d
      compression: xz
      encryption: aes256-ctr

    - key: s3-cheap-secure
      name: Nearline (Secure)
      description: |
        Cheap, fast, always-available cloud storage,
        on Amazon AWS, with ZERO dependencies on our
        VPCs, cross-connects, and backhaul network.

      maxSnapshotRetention: 90d
      compression: none
      encryption: aes256-gcm

      vault: *kms

      kind: s3
      s3: *cheap

    - key: enclave1
      name: Enclave
      description: |
        Secure Data Enclave, inside the confines of
        our Atlanta data center(s).  Please use this
        for data under compliance (PCI, HIPAA, etc.)

      kind: webdav
      webdav:
        url: https://secure.data.enclave:9097/nas13
        username: $NAS_USERNAME
        password: $NAS_PASSWORD
        caCertificate:
          file: /path/to/file
```

The dynamic endpoint for discovering the public information about configured buckets would look like this:

```
GET /buckets
```

... with a JSON response payload of:

```
[
  {
    "key": "s3-cheap",
    "name": "Nearline (Compressed)",
    "description": "Cheap, fast, always-available cloud storage, on Amazon AWS, with ZERO dependencies on our VPCs, cross-connects, and backhaul network.",
    "maxSnapshotRetention": 7776000, # seconds
    "compression": "xz",
    "encryption": "aes256-gcm"
  },
  {
    # etc.
  }
]
```
